### PR TITLE
Default offsets values able mzXML files

### PR DESCRIPTION
**Pull request by jsaintvanne**
We can run mzXML files with default values here for offsets... Can be good to remove them, but it may produce an error after that should be managed !

### CODE REVIEW

**Comment by jsaintvanne** [comment]
youps sorry Thomas I thought you were waiting for me to change it !

**Comment by Tomnl** [comment]
Thanks @jsaintvanne. Let me know if you find anything else. 

I will push the bug fix as  "v1.12.0+galaxy1" to the stable toolshed tomorrow.

**Comment by bgruening** [comment]
@jsaintvanne please bump the tool version number in this cases. The reason is that we then get a new galaxy tool version and the old one still keeps available for reproducibily ... :)

Thanks for you fix!

**Comment by Tomnl** [comment]
Thanks both. I can confirm that the bug fix will be updated as a new tool version in the toolshed.

**Pull request merged**
