### PR TITLE
v1.12.2+galaxy3 - fix reference to offsets in conditional

### PR DESCRIPTION
**Pull request by bernt-matthias**

### CODE REVIEW

**Comment by Tomnl** [comment]
Thanks for spotting this

**Comment by bernt-matthias** [comment]
Is this autoatically pushed to the toolshed? 

If not you may consider to switch to IUC style github actions. Should be as simple as to 
- copy the `.github/workflow` dir to this repo
- and to set a few secrets 

Then yoy have quite a bit of linting, weekly CI, and automatic deployment in the TTS and TS

**Comment by bernt-matthias** [comment]
This still needs an upload to the toolshed. 

If you like you we can automatize this like so https://github.com/computational-metabolomics/cfm-galaxy/pull/6. But ideally you would want to have a single tool repo. Alternatively your tools could also go to a central repo like W4M .. but I guess this is no option.

**Comment by Tomnl** [comment]
Hi both,

Sorry forgot to push this to the toolshed. The fixed tool should be available now to download directly via the toolshed.

@bernt-matthias - I agree, it  would be better to automate this - can I just copy the relevant section from cfm-galaxy repo? (I did something similar a while ago for some [other tools](https://github.com/computational-metabolomics/sirius-csifingerid-galaxy/blob/master/.travis.yml) but the approach looks a bit different now)

Also, eventually a central location for the tools might make sense at least for the computational-metabolomics tools - something @RJMW  and I should consider (but not really an option at the moment).

**Comment by bernt-matthias** [comment]
> can I just copy the relevant section from cfm-galaxy repo?

You can just copy the complete workflows. 

You also need to setup the API keys for the TTS and the TS as github secrets.

**Pull request merged**
